### PR TITLE
Add braces to staging table name to make it safe for reserved characters

### PR DESCRIPTION
**Pull request by whaitukay**
The NO_DUPLICATES strategy has been problematic for some as this strategy uses the appId to create staging tables.
The appId commonly contains dashes ( - ) and this then results in a failure: `Incorrect syntax near '-'.`

Adding braces around the name of the table will help mitigate this issue.
Relates to https://github.com/microsoft/sql-spark-connector/issues/22

### CODE REVIEW

**Review by arvindshmicrosoft — COMMENTED** [review]
In addition to this, consider the logic that is within the [QUOTENAME](https://docs.microsoft.com/en-us/sql/t-sql/functions/quotename-transact-sql) SQL function. QUOTENAME has more comprehensive logic handling other cases, including the case where there are embedded quotes.

**Comment by shivsood** [comment]
Fix looks good. @arvindshmicrosoft not clear what additional logic does QUOTENAME offer beyond enclosing in [].
@luxu1-ms for validation

**Comment by arvindshmicrosoft** [comment]
In this specialized use-case, @shivsood the enclosure with brackets is adequate. QUOTENAME handles the generic case when the string being enclosed itself has an embedded bracket etc. As long as Spark app IDs will never have an embedded `]` themselves, this simplistic fix is adequate.

**Review by shivsood — APPROVED** [review]

**Comment by shivsood** [comment]
Please add test results post this fix. 

@luxu1-ms

**Comment by shivsood** [comment]
@whihathac can u please add validation results please.

@luxu1-ms

**Comment by whihathac** [comment]
> @whihathac can u please add validation results please.
> 
> @luxu1-ms

I think you meant to tag @whaitukay :)

**Comment by shivsood** [comment]
@whihathac  can u please add the validation results.

**Comment by luxu1-ms** [comment]
@whaitukay Can you please add the validation results, or share the validation tests to me. Thank you.

**Review by luxu1-ms — APPROVED** [review]

**Comment by luxu1-ms** [comment]
Verified. (BDC: CI/GCI, DBR: sample cases)
Pls merge it @shivsood

**Comment by arvindshmicrosoft** [comment]
> Verified. (BDC: CI/GCI, DBR: sample cases)
> Pls merge it @shivsood

Looks like you need to rebase against / merge with current main branch. The tests are failing.

**Comment by arvindshmicrosoft** [comment]
@luxu1-ms @shivsood  - we should close this PR given the work was merged as part of #117

**Comment by luxu1-ms** [comment]
Merged as part of #117

**Pull request closed without merging**
